"""empty message

Revision ID: 05829c9d2a2d
Revises: 62b1a3cd781c
Create Date: 2024-09-05 15:51:53.650348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05829c9d2a2d'
down_revision = '62b1a3cd781c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
