"""increate password size

Revision ID: 62b1a3cd781c
Revises: ffb6cde6592a
Create Date: 2024-08-14 15:39:57.008634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1a3cd781c'
down_revision = 'ffb6cde6592a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitcompletion_table',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('userhabit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userhabit_id'], ['userhabit_table.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('habitcompletion_table')
    # ### end Alembic commands ###
